spring:
   application:
         name: ecom-config
   cloud:
     config:
      server: 
           git:
            uri: file:///home/arora/Desktop/PE/ecom/config-repo   

server:
  port: 8888

#file:/home/myname/Ecom-WS/Ecom-NoSec/Ecom/config-repo
